data-scalpel:
  dispatcher:
    runner:
      docker:
        commands:
          - "--security-opt"
          - "seccomp=unconfined"
          - "-v"
          - "/Users/huangchao/IdeaProjects/SuperHuang/DataScalpel/data-scalpel-task-actuator/target/:/data"
          - "eclipse-temurin:17.0.12_7-jre-jammy"
          - "java"
          - "-jar"
          - "/data/data-scalpel-task-actuator-0.0.1-SNAPSHOT-jar-with-dependencies.jar"
spring:
  kafka:
    consumer:
      group-id: superhuang